Replace textwrap with messenger.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,26 +1,26 @@
-#!/bin/csh -f
-set supportedPythonVersions=(2 3)
-set name=scripts
-rm -f install.out
+#!/bin/bash
+# Install into ~/.local for the versions of python listed in 'pythons' below.
+#
+# Requires Python2.7 or Python 3.3.
+cmd=scripts
+pythons=(python2 python3)
+    # Add the versions of python you would like to install to above
 
-# run pylint to find egregious errors
-# # this is optional, you can delete this line if you don't have pylint
-pylint -E --disable=no-member $name.py
+for python in ${pythons[*]}; do
+    # Determine the version of python we are using
+    vers=$($python -c 'import sys; print("%s.%s" % (sys.version_info[0], sys.version_info[1]))')
+    echo "Installing $cmd to ~/.home/bin (Python$vers)."
 
-foreach vers ($supportedPythonVersions)
+    # remove build directories from a previous install to assure a clean install
+    rm -rf build dist $cmd.egg-info install.out
 
-    # remove build directory from a previous install to assure a clean install
-    rm -rf build
+    # install $cmd
+    $python setup.py install --quiet --user >& install.out
+    if [[ $? -ne 0 ]] ; then
+        echo "Problems found, aborting (see install.out)"
+        exit 1
+    fi
+done
 
-    which python$vers >& /dev/null
-    if ($status == 0) then
-        echo "Installing $name to Python$vers."
-        python$vers setup.py install --quiet --user >>& install.out
-        if ($status) then
-            echo "Problems found, aborting (see install.out)"
-            exit(1)
-        endif
-    else
-        echo "Cannot install $name to Python$vers, it is not available."
-    endif
-end
+# remove build directories, because I like a clean directory
+rm -rf build dist $cmd.egg-info
